pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {

        stage('Create Virtual Environment') {
            steps {
                bat 'py -m venv %VENV%'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '.\\%VENV%\\Scripts\\python -m pip install --upgrade pip'
                bat '.\\%VENV%\\Scripts\\pip install -r notes-automation\\requirements.txt'
            }
        }

        stage('Start Selenium Grid') {
            steps {

                bat 'docker network create grid || exit 0'

                bat '''
                docker run -d --rm ^
                --name selenium-hub ^
                --network grid ^
                -p 4442:4442 ^
                -p 4443:4443 ^
                -p 4444:4444 ^
                selenium/hub:4.21.0
                '''

                bat '''
                docker run -d --rm ^
                --name chrome-node ^
                --network grid ^
                -e SE_EVENT_BUS_HOST=selenium-hub ^
                -e SE_EVENT_BUS_PUBLISH_PORT=4442 ^
                -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 ^
                selenium/node-chrome:4.21.0
                '''

                bat 'timeout /t 15'
            }
        }

        stage('Run Tests') {
            steps {
                dir('notes-automation') {
                    bat '..\\%VENV%\\Scripts\\python -m pytest -v --alluredir=allure-results'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                allure(
                    includeProperties: false,
                    results: [[path: 'notes-automation/allure-results']]
                )
            }
        }
    }

    post {

        always {

            archiveArtifacts artifacts: 'notes-automation/allure-results/**', fingerprint: true

            bat 'docker stop chrome-node || exit 0'
            bat 'docker stop selenium-hub || exit 0'
        }

        success {
            echo 'Pipeline executed successfully.'
        }

        failure {
            echo 'Some test cases failed or pipeline encountered issues.'
        }
    }
}